"use client";

import React, { useState } from "react";
import { Download, ReceiptText, FileText, Wallet } from "lucide-react";
import { TopBar } from "@/components/mobile/TopBar";
import { EmptyState } from "@/components/ui/Misc";
import { Illustration } from "@/components/media/Illustration";
import { useApp, useMemberData } from "@/lib/store";
import { formatDate, formatKwacha } from "@/lib/format";
import type { Statement, StatementType } from "@/types";

const tabs: ("All" | StatementType)[] = [
  "All",
  "Membership Receipt",
  "Submission Receipt",
  "Royalty Statement",
];

const icon: Record<StatementType, React.ComponentType<{ size?: number }>> = {
  "Membership Receipt": ReceiptText,
  "Submission Receipt": FileText,
  "Royalty Statement": Wallet,
};

export default function StatementsScreen() {
  const { currentMember } = useApp();
  const { statements } = useMemberData();
  const [tab, setTab] = useState<(typeof tabs)[number]>("All");
  const shown = statements.filter((s) => tab === "All" || s.type === tab);

  // Generates a simple downloadable receipt/statement document (no backend yet).
  const download = (s: Statement) => {
    const lines = [
      "ZAMCOPS — Zambian Music Copyright Protection Society",
      "============================================",
      `Document type : ${s.type}`,
      `Title         : ${s.title}`,
      `Reference     : ${s.reference}`,
      `Member        : ${currentMember?.fullName} (${currentMember?.memberNumber})`,
      `Issued        : ${formatDate(s.issuedAt)}`,
      s.amount != null ? `Amount        : ${formatKwacha(s.amount)}` : "",
      "",
      "This document is computer-generated by the ZAMCOPS member portal.",
    ].filter(Boolean);
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${s.reference}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div>
      <TopBar title="Statements & Receipts" back="/dashboard" />

      <div className="px-4 py-4">
        <div className="no-scrollbar -mx-1 mb-4 flex gap-2 overflow-x-auto px-1">
          {tabs.map((t) => (
            <button
              key={t}
              onClick={() => setTab(t)}
              className={
                "shrink-0 rounded-full px-4 py-1.5 text-xs font-semibold transition " +
                (tab === t ? "bg-accent-500 text-night-950 ring-1 ring-accent-300/30" : "border border-white/10 bg-white/[0.05] text-night-300 hover:bg-white/[0.08]")
              }
            >
              {t === "All" ? "All" : t.replace(" Receipt", "").replace(" Statement", "")}
            </button>
          ))}
        </div>

        {shown.length === 0 ? (
          <EmptyState
            art={<Illustration name="vinyl" />}
            title="No documents yet"
            message="Receipts and statements are generated as you register, submit and earn royalties."
          />
        ) : (
          <div className="space-y-3">
            {shown.map((s) => {
              const Icon = icon[s.type];
              return (
                <div key={s.id} className="card flex items-center gap-3 px-4 py-3.5">
                  <span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white/[0.06] text-brand-300 ring-1 ring-white/10">
                    <Icon size={18} />
                  </span>
                  <div className="min-w-0 flex-1">
                    <p className="truncate text-sm font-semibold text-white">{s.title}</p>
                    <p className="truncate text-xs text-night-400">
                      {s.reference} · {formatDate(s.issuedAt)}
                      {s.amount != null ? ` · ${formatKwacha(s.amount)}` : ""}
                    </p>
                  </div>
                  <button
                    onClick={() => download(s)}
                    className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-white/[0.06] text-brand-300 ring-1 ring-white/10 hover:bg-white/[0.1]"
                    aria-label="Download"
                  >
                    <Download size={16} />
                  </button>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
