"use client";

import { jsPDF } from "jspdf";
import type { Member, Statement } from "@/types";
import { formatDate, formatKwacha } from "@/lib/format";

// Brand colours (kept in sync with tailwind's zam palette).
const INK: [number, number, number] = [26, 29, 33];
const MUTED: [number, number, number] = [90, 100, 112];
const ORANGE: [number, number, number] = [242, 108, 33];
const LINE: [number, number, number] = [231, 233, 237];
const FLAG: [number, number, number][] = [
  [242, 108, 33],
  [226, 52, 43],
  [201, 206, 218],
  [43, 164, 90],
];

// Renders a branded A4 receipt/statement and triggers the download.
export function downloadStatementPDF(statement: Statement, member: Member) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const W = 210;
  const M = 20; // page margin

  // Header band
  doc.setFillColor(...INK);
  doc.rect(0, 0, W, 34, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("ZAMCOPS", M, 15);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("Zambian Music Copyright Protection Society", M, 21);
  doc.setFontSize(8);
  doc.setTextColor(200, 200, 200);
  doc.text("ZAMCOPS House, Lusaka, Zambia · info@zamcops.org.zm · +260 211 250 082", M, 27);

  // Zambian flagline under the header
  const flagW = (W - M * 2) / 4;
  FLAG.forEach((c, i) => {
    doc.setFillColor(...c);
    doc.rect(M + i * flagW, 38, flagW, 1.4, "F");
  });

  // Document title
  doc.setTextColor(...ORANGE);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(statement.type.toUpperCase(), M, 52);
  doc.setTextColor(...INK);
  doc.setFontSize(17);
  doc.text(statement.title, M, 61);

  // Details table
  const rows: [string, string][] = [
    ["Reference", statement.reference],
    ["Issued", formatDate(statement.issuedAt)],
    ["Member", `${member.fullName} (${member.memberNumber})`],
    ["Role", member.role],
  ];
  if (member.stageName) rows.splice(3, 0, ["Stage name", member.stageName]);

  let y = 74;
  doc.setFontSize(10);
  rows.forEach(([label, value]) => {
    doc.setDrawColor(...LINE);
    doc.line(M, y + 3.5, W - M, y + 3.5);
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    doc.text(label, M, y);
    doc.setTextColor(...INK);
    doc.setFont("helvetica", "bold");
    doc.text(value, W - M, y, { align: "right" });
    y += 10;
  });

  // Amount block
  if (statement.amount != null) {
    y += 6;
    doc.setFillColor(250, 240, 233);
    doc.roundedRect(M, y - 6, W - M * 2, 20, 2.5, 2.5, "F");
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text("AMOUNT", M + 6, y + 1);
    doc.setTextColor(...ORANGE);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text(formatKwacha(statement.amount), W - M - 6, y + 6, { align: "right" });
    y += 22;
  }

  // Footer
  doc.setTextColor(...MUTED);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text(
    "This document was generated by the ZAMCOPS member portal and is valid without a signature.",
    M,
    282
  );
  doc.text(`Generated ${formatDate(new Date().toISOString())}`, W - M, 282, { align: "right" });

  doc.save(`${statement.reference}.pdf`);
}
